/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAccessDeniedRouteImport } from './routes/_app/access-denied'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppAdmissionsIndexRouteImport } from './routes/_app/admissions/index'
import { Route as AppQualityResearchRouteImport } from './routes/_app/quality/research'
import { Route as AppQualityIqacRouteImport } from './routes/_app/quality/iqac'
import { Route as AppQualityGrievancesRouteImport } from './routes/_app/quality/grievances'
import { Route as AppPlacementOffersRouteImport } from './routes/_app/placement/offers'
import { Route as AppPlacementJobProfilesRouteImport } from './routes/_app/placement/job-profiles'
import { Route as AppPlacementDrivesRouteImport } from './routes/_app/placement/drives'
import { Route as AppPlacementCompaniesRouteImport } from './routes/_app/placement/companies'
import { Route as AppPlacementAiInterviewsRouteImport } from './routes/_app/placement/ai-interviews'
import { Route as AppPlacementAiAssessmentsRouteImport } from './routes/_app/placement/ai-assessments'
import { Route as AppPeopleStudentsRouteImport } from './routes/_app/people/students'
import { Route as AppPeopleParentsRouteImport } from './routes/_app/people/parents'
import { Route as AppPeopleFacultyAppraisalRouteImport } from './routes/_app/people/faculty-appraisal'
import { Route as AppPeopleFacultyRouteImport } from './routes/_app/people/faculty'
import { Route as AppPeopleAlumniRouteImport } from './routes/_app/people/alumni'
import { Route as AppMyResultsRouteImport } from './routes/_app/my/results'
import { Route as AppMyFeesRouteImport } from './routes/_app/my/fees'
import { Route as AppFinanceScholarshipsRouteImport } from './routes/_app/finance/scholarships'
import { Route as AppFinanceLedgerRouteImport } from './routes/_app/finance/ledger'
import { Route as AppFinanceFeeStructuresRouteImport } from './routes/_app/finance/fee-structures'
import { Route as AppFinanceDefaultersRouteImport } from './routes/_app/finance/defaulters'
import { Route as AppFinanceBudgetRouteImport } from './routes/_app/finance/budget'
import { Route as AppComplianceNirfRouteImport } from './routes/_app/compliance/nirf'
import { Route as AppComplianceNbaRouteImport } from './routes/_app/compliance/nba'
import { Route as AppComplianceNaacRouteImport } from './routes/_app/compliance/naac'
import { Route as AppComplianceAicteRouteImport } from './routes/_app/compliance/aicte'
import { Route as AppCommunicationInboxRouteImport } from './routes/_app/communication/inbox'
import { Route as AppCommunicationAnnouncementsRouteImport } from './routes/_app/communication/announcements'
import { Route as AppAnalyticsReportsRouteImport } from './routes/_app/analytics/reports'
import { Route as AppAdminTransportRouteImport } from './routes/_app/admin/transport'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'
import { Route as AppAdminProcurementRouteImport } from './routes/_app/admin/procurement'
import { Route as AppAdminOrgStructureRouteImport } from './routes/_app/admin/org-structure'
import { Route as AppAdminHostelRouteImport } from './routes/_app/admin/hostel'
import { Route as AppAdminCommitteesRouteImport } from './routes/_app/admin/committees'
import { Route as AppAdminAuditLogRouteImport } from './routes/_app/admin/audit-log'
import { Route as AppAdminApprovalsRouteImport } from './routes/_app/admin/approvals'
import { Route as AppAcademicTimetableRouteImport } from './routes/_app/academic/timetable'
import { Route as AppAcademicSubjectsRouteImport } from './routes/_app/academic/subjects'
import { Route as AppAcademicStudyMaterialRouteImport } from './routes/_app/academic/study-material'
import { Route as AppAcademicResultsRouteImport } from './routes/_app/academic/results'
import { Route as AppAcademicProgramsRouteImport } from './routes/_app/academic/programs'
import { Route as AppAcademicLibraryRouteImport } from './routes/_app/academic/library'
import { Route as AppAcademicExaminationsRouteImport } from './routes/_app/academic/examinations'
import { Route as AppAcademicCourseFilesRouteImport } from './routes/_app/academic/course-files'
import { Route as AppAcademicClassesRouteImport } from './routes/_app/academic/classes'
import { Route as AppAcademicCertificatesRouteImport } from './routes/_app/academic/certificates'
import { Route as AppAcademicCalendarRouteImport } from './routes/_app/academic/calendar'
import { Route as AppAcademicAttendanceRouteImport } from './routes/_app/academic/attendance'
import { Route as AppAdminAccessControlIndexRouteImport } from './routes/_app/admin/access-control/index'
import { Route as AppPlacementDrivesIdRouteImport } from './routes/_app/placement/drives.$id'
import { Route as AppPlacementAiAssessmentsTakeRouteImport } from './routes/_app/placement/ai-assessments.take'
import { Route as AppPeopleStudentsIdRouteImport } from './routes/_app/people/students.$id'
import { Route as AppAdminAccessControlRequestsRouteImport } from './routes/_app/admin/access-control/requests'
import { Route as AppAdminAccessControlPeopleRouteImport } from './routes/_app/admin/access-control/people'
import { Route as AppAdminAccessControlActivityRouteImport } from './routes/_app/admin/access-control/activity'
import { Route as AppAdminAccessControlAccessPacksRouteImport } from './routes/_app/admin/access-control/access-packs'
import { Route as AppAcademicExaminationsIdRouteImport } from './routes/_app/academic/examinations.$id'
import { Route as AppAdminAccessControlUsersIdRouteImport } from './routes/_app/admin/access-control/users.$id'
import { Route as AppAdminAccessControlAccessPacksIdRouteImport } from './routes/_app/admin/access-control/access-packs.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessDeniedRoute = AppAccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAdmissionsIndexRoute = AppAdmissionsIndexRouteImport.update({
  id: '/admissions/',
  path: '/admissions/',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityResearchRoute = AppQualityResearchRouteImport.update({
  id: '/quality/research',
  path: '/quality/research',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityIqacRoute = AppQualityIqacRouteImport.update({
  id: '/quality/iqac',
  path: '/quality/iqac',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityGrievancesRoute = AppQualityGrievancesRouteImport.update({
  id: '/quality/grievances',
  path: '/quality/grievances',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacementOffersRoute = AppPlacementOffersRouteImport.update({
  id: '/placement/offers',
  path: '/placement/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacementJobProfilesRoute = AppPlacementJobProfilesRouteImport.update({
  id: '/placement/job-profiles',
  path: '/placement/job-profiles',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacementDrivesRoute = AppPlacementDrivesRouteImport.update({
  id: '/placement/drives',
  path: '/placement/drives',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacementCompaniesRoute = AppPlacementCompaniesRouteImport.update({
  id: '/placement/companies',
  path: '/placement/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacementAiInterviewsRoute =
  AppPlacementAiInterviewsRouteImport.update({
    id: '/placement/ai-interviews',
    path: '/placement/ai-interviews',
    getParentRoute: () => AppRoute,
  } as any)
const AppPlacementAiAssessmentsRoute =
  AppPlacementAiAssessmentsRouteImport.update({
    id: '/placement/ai-assessments',
    path: '/placement/ai-assessments',
    getParentRoute: () => AppRoute,
  } as any)
const AppPeopleStudentsRoute = AppPeopleStudentsRouteImport.update({
  id: '/people/students',
  path: '/people/students',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleParentsRoute = AppPeopleParentsRouteImport.update({
  id: '/people/parents',
  path: '/people/parents',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleFacultyAppraisalRoute =
  AppPeopleFacultyAppraisalRouteImport.update({
    id: '/people/faculty-appraisal',
    path: '/people/faculty-appraisal',
    getParentRoute: () => AppRoute,
  } as any)
const AppPeopleFacultyRoute = AppPeopleFacultyRouteImport.update({
  id: '/people/faculty',
  path: '/people/faculty',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleAlumniRoute = AppPeopleAlumniRouteImport.update({
  id: '/people/alumni',
  path: '/people/alumni',
  getParentRoute: () => AppRoute,
} as any)
const AppMyResultsRoute = AppMyResultsRouteImport.update({
  id: '/my/results',
  path: '/my/results',
  getParentRoute: () => AppRoute,
} as any)
const AppMyFeesRoute = AppMyFeesRouteImport.update({
  id: '/my/fees',
  path: '/my/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceScholarshipsRoute = AppFinanceScholarshipsRouteImport.update({
  id: '/finance/scholarships',
  path: '/finance/scholarships',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceLedgerRoute = AppFinanceLedgerRouteImport.update({
  id: '/finance/ledger',
  path: '/finance/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceFeeStructuresRoute = AppFinanceFeeStructuresRouteImport.update({
  id: '/finance/fee-structures',
  path: '/finance/fee-structures',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceDefaultersRoute = AppFinanceDefaultersRouteImport.update({
  id: '/finance/defaulters',
  path: '/finance/defaulters',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceBudgetRoute = AppFinanceBudgetRouteImport.update({
  id: '/finance/budget',
  path: '/finance/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceNirfRoute = AppComplianceNirfRouteImport.update({
  id: '/compliance/nirf',
  path: '/compliance/nirf',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceNbaRoute = AppComplianceNbaRouteImport.update({
  id: '/compliance/nba',
  path: '/compliance/nba',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceNaacRoute = AppComplianceNaacRouteImport.update({
  id: '/compliance/naac',
  path: '/compliance/naac',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceAicteRoute = AppComplianceAicteRouteImport.update({
  id: '/compliance/aicte',
  path: '/compliance/aicte',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunicationInboxRoute = AppCommunicationInboxRouteImport.update({
  id: '/communication/inbox',
  path: '/communication/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunicationAnnouncementsRoute =
  AppCommunicationAnnouncementsRouteImport.update({
    id: '/communication/announcements',
    path: '/communication/announcements',
    getParentRoute: () => AppRoute,
  } as any)
const AppAnalyticsReportsRoute = AppAnalyticsReportsRouteImport.update({
  id: '/analytics/reports',
  path: '/analytics/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTransportRoute = AppAdminTransportRouteImport.update({
  id: '/admin/transport',
  path: '/admin/transport',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminProcurementRoute = AppAdminProcurementRouteImport.update({
  id: '/admin/procurement',
  path: '/admin/procurement',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOrgStructureRoute = AppAdminOrgStructureRouteImport.update({
  id: '/admin/org-structure',
  path: '/admin/org-structure',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminHostelRoute = AppAdminHostelRouteImport.update({
  id: '/admin/hostel',
  path: '/admin/hostel',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCommitteesRoute = AppAdminCommitteesRouteImport.update({
  id: '/admin/committees',
  path: '/admin/committees',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditLogRoute = AppAdminAuditLogRouteImport.update({
  id: '/admin/audit-log',
  path: '/admin/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminApprovalsRoute = AppAdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicTimetableRoute = AppAcademicTimetableRouteImport.update({
  id: '/academic/timetable',
  path: '/academic/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicSubjectsRoute = AppAcademicSubjectsRouteImport.update({
  id: '/academic/subjects',
  path: '/academic/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicStudyMaterialRoute =
  AppAcademicStudyMaterialRouteImport.update({
    id: '/academic/study-material',
    path: '/academic/study-material',
    getParentRoute: () => AppRoute,
  } as any)
const AppAcademicResultsRoute = AppAcademicResultsRouteImport.update({
  id: '/academic/results',
  path: '/academic/results',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicProgramsRoute = AppAcademicProgramsRouteImport.update({
  id: '/academic/programs',
  path: '/academic/programs',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicLibraryRoute = AppAcademicLibraryRouteImport.update({
  id: '/academic/library',
  path: '/academic/library',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicExaminationsRoute = AppAcademicExaminationsRouteImport.update({
  id: '/academic/examinations',
  path: '/academic/examinations',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicCourseFilesRoute = AppAcademicCourseFilesRouteImport.update({
  id: '/academic/course-files',
  path: '/academic/course-files',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicClassesRoute = AppAcademicClassesRouteImport.update({
  id: '/academic/classes',
  path: '/academic/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicCertificatesRoute = AppAcademicCertificatesRouteImport.update({
  id: '/academic/certificates',
  path: '/academic/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicCalendarRoute = AppAcademicCalendarRouteImport.update({
  id: '/academic/calendar',
  path: '/academic/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicAttendanceRoute = AppAcademicAttendanceRouteImport.update({
  id: '/academic/attendance',
  path: '/academic/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAccessControlIndexRoute =
  AppAdminAccessControlIndexRouteImport.update({
    id: '/admin/access-control/',
    path: '/admin/access-control/',
    getParentRoute: () => AppRoute,
  } as any)
const AppPlacementDrivesIdRoute = AppPlacementDrivesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPlacementDrivesRoute,
} as any)
const AppPlacementAiAssessmentsTakeRoute =
  AppPlacementAiAssessmentsTakeRouteImport.update({
    id: '/take',
    path: '/take',
    getParentRoute: () => AppPlacementAiAssessmentsRoute,
  } as any)
const AppPeopleStudentsIdRoute = AppPeopleStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPeopleStudentsRoute,
} as any)
const AppAdminAccessControlRequestsRoute =
  AppAdminAccessControlRequestsRouteImport.update({
    id: '/admin/access-control/requests',
    path: '/admin/access-control/requests',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminAccessControlPeopleRoute =
  AppAdminAccessControlPeopleRouteImport.update({
    id: '/admin/access-control/people',
    path: '/admin/access-control/people',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminAccessControlActivityRoute =
  AppAdminAccessControlActivityRouteImport.update({
    id: '/admin/access-control/activity',
    path: '/admin/access-control/activity',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminAccessControlAccessPacksRoute =
  AppAdminAccessControlAccessPacksRouteImport.update({
    id: '/admin/access-control/access-packs',
    path: '/admin/access-control/access-packs',
    getParentRoute: () => AppRoute,
  } as any)
const AppAcademicExaminationsIdRoute =
  AppAcademicExaminationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppAcademicExaminationsRoute,
  } as any)
const AppAdminAccessControlUsersIdRoute =
  AppAdminAccessControlUsersIdRouteImport.update({
    id: '/admin/access-control/users/$id',
    path: '/admin/access-control/users/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminAccessControlAccessPacksIdRoute =
  AppAdminAccessControlAccessPacksIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppAdminAccessControlAccessPacksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/access-denied': typeof AppAccessDeniedRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/academic/attendance': typeof AppAcademicAttendanceRoute
  '/academic/calendar': typeof AppAcademicCalendarRoute
  '/academic/certificates': typeof AppAcademicCertificatesRoute
  '/academic/classes': typeof AppAcademicClassesRoute
  '/academic/course-files': typeof AppAcademicCourseFilesRoute
  '/academic/examinations': typeof AppAcademicExaminationsRouteWithChildren
  '/academic/library': typeof AppAcademicLibraryRoute
  '/academic/programs': typeof AppAcademicProgramsRoute
  '/academic/results': typeof AppAcademicResultsRoute
  '/academic/study-material': typeof AppAcademicStudyMaterialRoute
  '/academic/subjects': typeof AppAcademicSubjectsRoute
  '/academic/timetable': typeof AppAcademicTimetableRoute
  '/admin/approvals': typeof AppAdminApprovalsRoute
  '/admin/audit-log': typeof AppAdminAuditLogRoute
  '/admin/committees': typeof AppAdminCommitteesRoute
  '/admin/hostel': typeof AppAdminHostelRoute
  '/admin/org-structure': typeof AppAdminOrgStructureRoute
  '/admin/procurement': typeof AppAdminProcurementRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/transport': typeof AppAdminTransportRoute
  '/analytics/reports': typeof AppAnalyticsReportsRoute
  '/communication/announcements': typeof AppCommunicationAnnouncementsRoute
  '/communication/inbox': typeof AppCommunicationInboxRoute
  '/compliance/aicte': typeof AppComplianceAicteRoute
  '/compliance/naac': typeof AppComplianceNaacRoute
  '/compliance/nba': typeof AppComplianceNbaRoute
  '/compliance/nirf': typeof AppComplianceNirfRoute
  '/finance/budget': typeof AppFinanceBudgetRoute
  '/finance/defaulters': typeof AppFinanceDefaultersRoute
  '/finance/fee-structures': typeof AppFinanceFeeStructuresRoute
  '/finance/ledger': typeof AppFinanceLedgerRoute
  '/finance/scholarships': typeof AppFinanceScholarshipsRoute
  '/my/fees': typeof AppMyFeesRoute
  '/my/results': typeof AppMyResultsRoute
  '/people/alumni': typeof AppPeopleAlumniRoute
  '/people/faculty': typeof AppPeopleFacultyRoute
  '/people/faculty-appraisal': typeof AppPeopleFacultyAppraisalRoute
  '/people/parents': typeof AppPeopleParentsRoute
  '/people/students': typeof AppPeopleStudentsRouteWithChildren
  '/placement/ai-assessments': typeof AppPlacementAiAssessmentsRouteWithChildren
  '/placement/ai-interviews': typeof AppPlacementAiInterviewsRoute
  '/placement/companies': typeof AppPlacementCompaniesRoute
  '/placement/drives': typeof AppPlacementDrivesRouteWithChildren
  '/placement/job-profiles': typeof AppPlacementJobProfilesRoute
  '/placement/offers': typeof AppPlacementOffersRoute
  '/quality/grievances': typeof AppQualityGrievancesRoute
  '/quality/iqac': typeof AppQualityIqacRoute
  '/quality/research': typeof AppQualityResearchRoute
  '/admissions/': typeof AppAdmissionsIndexRoute
  '/academic/examinations/$id': typeof AppAcademicExaminationsIdRoute
  '/admin/access-control/access-packs': typeof AppAdminAccessControlAccessPacksRouteWithChildren
  '/admin/access-control/activity': typeof AppAdminAccessControlActivityRoute
  '/admin/access-control/people': typeof AppAdminAccessControlPeopleRoute
  '/admin/access-control/requests': typeof AppAdminAccessControlRequestsRoute
  '/people/students/$id': typeof AppPeopleStudentsIdRoute
  '/placement/ai-assessments/take': typeof AppPlacementAiAssessmentsTakeRoute
  '/placement/drives/$id': typeof AppPlacementDrivesIdRoute
  '/admin/access-control/': typeof AppAdminAccessControlIndexRoute
  '/admin/access-control/access-packs/$id': typeof AppAdminAccessControlAccessPacksIdRoute
  '/admin/access-control/users/$id': typeof AppAdminAccessControlUsersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/access-denied': typeof AppAccessDeniedRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/academic/attendance': typeof AppAcademicAttendanceRoute
  '/academic/calendar': typeof AppAcademicCalendarRoute
  '/academic/certificates': typeof AppAcademicCertificatesRoute
  '/academic/classes': typeof AppAcademicClassesRoute
  '/academic/course-files': typeof AppAcademicCourseFilesRoute
  '/academic/examinations': typeof AppAcademicExaminationsRouteWithChildren
  '/academic/library': typeof AppAcademicLibraryRoute
  '/academic/programs': typeof AppAcademicProgramsRoute
  '/academic/results': typeof AppAcademicResultsRoute
  '/academic/study-material': typeof AppAcademicStudyMaterialRoute
  '/academic/subjects': typeof AppAcademicSubjectsRoute
  '/academic/timetable': typeof AppAcademicTimetableRoute
  '/admin/approvals': typeof AppAdminApprovalsRoute
  '/admin/audit-log': typeof AppAdminAuditLogRoute
  '/admin/committees': typeof AppAdminCommitteesRoute
  '/admin/hostel': typeof AppAdminHostelRoute
  '/admin/org-structure': typeof AppAdminOrgStructureRoute
  '/admin/procurement': typeof AppAdminProcurementRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/transport': typeof AppAdminTransportRoute
  '/analytics/reports': typeof AppAnalyticsReportsRoute
  '/communication/announcements': typeof AppCommunicationAnnouncementsRoute
  '/communication/inbox': typeof AppCommunicationInboxRoute
  '/compliance/aicte': typeof AppComplianceAicteRoute
  '/compliance/naac': typeof AppComplianceNaacRoute
  '/compliance/nba': typeof AppComplianceNbaRoute
  '/compliance/nirf': typeof AppComplianceNirfRoute
  '/finance/budget': typeof AppFinanceBudgetRoute
  '/finance/defaulters': typeof AppFinanceDefaultersRoute
  '/finance/fee-structures': typeof AppFinanceFeeStructuresRoute
  '/finance/ledger': typeof AppFinanceLedgerRoute
  '/finance/scholarships': typeof AppFinanceScholarshipsRoute
  '/my/fees': typeof AppMyFeesRoute
  '/my/results': typeof AppMyResultsRoute
  '/people/alumni': typeof AppPeopleAlumniRoute
  '/people/faculty': typeof AppPeopleFacultyRoute
  '/people/faculty-appraisal': typeof AppPeopleFacultyAppraisalRoute
  '/people/parents': typeof AppPeopleParentsRoute
  '/people/students': typeof AppPeopleStudentsRouteWithChildren
  '/placement/ai-assessments': typeof AppPlacementAiAssessmentsRouteWithChildren
  '/placement/ai-interviews': typeof AppPlacementAiInterviewsRoute
  '/placement/companies': typeof AppPlacementCompaniesRoute
  '/placement/drives': typeof AppPlacementDrivesRouteWithChildren
  '/placement/job-profiles': typeof AppPlacementJobProfilesRoute
  '/placement/offers': typeof AppPlacementOffersRoute
  '/quality/grievances': typeof AppQualityGrievancesRoute
  '/quality/iqac': typeof AppQualityIqacRoute
  '/quality/research': typeof AppQualityResearchRoute
  '/admissions': typeof AppAdmissionsIndexRoute
  '/academic/examinations/$id': typeof AppAcademicExaminationsIdRoute
  '/admin/access-control/access-packs': typeof AppAdminAccessControlAccessPacksRouteWithChildren
  '/admin/access-control/activity': typeof AppAdminAccessControlActivityRoute
  '/admin/access-control/people': typeof AppAdminAccessControlPeopleRoute
  '/admin/access-control/requests': typeof AppAdminAccessControlRequestsRoute
  '/people/students/$id': typeof AppPeopleStudentsIdRoute
  '/placement/ai-assessments/take': typeof AppPlacementAiAssessmentsTakeRoute
  '/placement/drives/$id': typeof AppPlacementDrivesIdRoute
  '/admin/access-control': typeof AppAdminAccessControlIndexRoute
  '/admin/access-control/access-packs/$id': typeof AppAdminAccessControlAccessPacksIdRoute
  '/admin/access-control/users/$id': typeof AppAdminAccessControlUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/access-denied': typeof AppAccessDeniedRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/academic/attendance': typeof AppAcademicAttendanceRoute
  '/_app/academic/calendar': typeof AppAcademicCalendarRoute
  '/_app/academic/certificates': typeof AppAcademicCertificatesRoute
  '/_app/academic/classes': typeof AppAcademicClassesRoute
  '/_app/academic/course-files': typeof AppAcademicCourseFilesRoute
  '/_app/academic/examinations': typeof AppAcademicExaminationsRouteWithChildren
  '/_app/academic/library': typeof AppAcademicLibraryRoute
  '/_app/academic/programs': typeof AppAcademicProgramsRoute
  '/_app/academic/results': typeof AppAcademicResultsRoute
  '/_app/academic/study-material': typeof AppAcademicStudyMaterialRoute
  '/_app/academic/subjects': typeof AppAcademicSubjectsRoute
  '/_app/academic/timetable': typeof AppAcademicTimetableRoute
  '/_app/admin/approvals': typeof AppAdminApprovalsRoute
  '/_app/admin/audit-log': typeof AppAdminAuditLogRoute
  '/_app/admin/committees': typeof AppAdminCommitteesRoute
  '/_app/admin/hostel': typeof AppAdminHostelRoute
  '/_app/admin/org-structure': typeof AppAdminOrgStructureRoute
  '/_app/admin/procurement': typeof AppAdminProcurementRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/transport': typeof AppAdminTransportRoute
  '/_app/analytics/reports': typeof AppAnalyticsReportsRoute
  '/_app/communication/announcements': typeof AppCommunicationAnnouncementsRoute
  '/_app/communication/inbox': typeof AppCommunicationInboxRoute
  '/_app/compliance/aicte': typeof AppComplianceAicteRoute
  '/_app/compliance/naac': typeof AppComplianceNaacRoute
  '/_app/compliance/nba': typeof AppComplianceNbaRoute
  '/_app/compliance/nirf': typeof AppComplianceNirfRoute
  '/_app/finance/budget': typeof AppFinanceBudgetRoute
  '/_app/finance/defaulters': typeof AppFinanceDefaultersRoute
  '/_app/finance/fee-structures': typeof AppFinanceFeeStructuresRoute
  '/_app/finance/ledger': typeof AppFinanceLedgerRoute
  '/_app/finance/scholarships': typeof AppFinanceScholarshipsRoute
  '/_app/my/fees': typeof AppMyFeesRoute
  '/_app/my/results': typeof AppMyResultsRoute
  '/_app/people/alumni': typeof AppPeopleAlumniRoute
  '/_app/people/faculty': typeof AppPeopleFacultyRoute
  '/_app/people/faculty-appraisal': typeof AppPeopleFacultyAppraisalRoute
  '/_app/people/parents': typeof AppPeopleParentsRoute
  '/_app/people/students': typeof AppPeopleStudentsRouteWithChildren
  '/_app/placement/ai-assessments': typeof AppPlacementAiAssessmentsRouteWithChildren
  '/_app/placement/ai-interviews': typeof AppPlacementAiInterviewsRoute
  '/_app/placement/companies': typeof AppPlacementCompaniesRoute
  '/_app/placement/drives': typeof AppPlacementDrivesRouteWithChildren
  '/_app/placement/job-profiles': typeof AppPlacementJobProfilesRoute
  '/_app/placement/offers': typeof AppPlacementOffersRoute
  '/_app/quality/grievances': typeof AppQualityGrievancesRoute
  '/_app/quality/iqac': typeof AppQualityIqacRoute
  '/_app/quality/research': typeof AppQualityResearchRoute
  '/_app/admissions/': typeof AppAdmissionsIndexRoute
  '/_app/academic/examinations/$id': typeof AppAcademicExaminationsIdRoute
  '/_app/admin/access-control/access-packs': typeof AppAdminAccessControlAccessPacksRouteWithChildren
  '/_app/admin/access-control/activity': typeof AppAdminAccessControlActivityRoute
  '/_app/admin/access-control/people': typeof AppAdminAccessControlPeopleRoute
  '/_app/admin/access-control/requests': typeof AppAdminAccessControlRequestsRoute
  '/_app/people/students/$id': typeof AppPeopleStudentsIdRoute
  '/_app/placement/ai-assessments/take': typeof AppPlacementAiAssessmentsTakeRoute
  '/_app/placement/drives/$id': typeof AppPlacementDrivesIdRoute
  '/_app/admin/access-control/': typeof AppAdminAccessControlIndexRoute
  '/_app/admin/access-control/access-packs/$id': typeof AppAdminAccessControlAccessPacksIdRoute
  '/_app/admin/access-control/users/$id': typeof AppAdminAccessControlUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/$'
    | '/access-denied'
    | '/dashboard'
    | '/profile'
    | '/academic/attendance'
    | '/academic/calendar'
    | '/academic/certificates'
    | '/academic/classes'
    | '/academic/course-files'
    | '/academic/examinations'
    | '/academic/library'
    | '/academic/programs'
    | '/academic/results'
    | '/academic/study-material'
    | '/academic/subjects'
    | '/academic/timetable'
    | '/admin/approvals'
    | '/admin/audit-log'
    | '/admin/committees'
    | '/admin/hostel'
    | '/admin/org-structure'
    | '/admin/procurement'
    | '/admin/settings'
    | '/admin/transport'
    | '/analytics/reports'
    | '/communication/announcements'
    | '/communication/inbox'
    | '/compliance/aicte'
    | '/compliance/naac'
    | '/compliance/nba'
    | '/compliance/nirf'
    | '/finance/budget'
    | '/finance/defaulters'
    | '/finance/fee-structures'
    | '/finance/ledger'
    | '/finance/scholarships'
    | '/my/fees'
    | '/my/results'
    | '/people/alumni'
    | '/people/faculty'
    | '/people/faculty-appraisal'
    | '/people/parents'
    | '/people/students'
    | '/placement/ai-assessments'
    | '/placement/ai-interviews'
    | '/placement/companies'
    | '/placement/drives'
    | '/placement/job-profiles'
    | '/placement/offers'
    | '/quality/grievances'
    | '/quality/iqac'
    | '/quality/research'
    | '/admissions/'
    | '/academic/examinations/$id'
    | '/admin/access-control/access-packs'
    | '/admin/access-control/activity'
    | '/admin/access-control/people'
    | '/admin/access-control/requests'
    | '/people/students/$id'
    | '/placement/ai-assessments/take'
    | '/placement/drives/$id'
    | '/admin/access-control/'
    | '/admin/access-control/access-packs/$id'
    | '/admin/access-control/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/$'
    | '/access-denied'
    | '/dashboard'
    | '/profile'
    | '/academic/attendance'
    | '/academic/calendar'
    | '/academic/certificates'
    | '/academic/classes'
    | '/academic/course-files'
    | '/academic/examinations'
    | '/academic/library'
    | '/academic/programs'
    | '/academic/results'
    | '/academic/study-material'
    | '/academic/subjects'
    | '/academic/timetable'
    | '/admin/approvals'
    | '/admin/audit-log'
    | '/admin/committees'
    | '/admin/hostel'
    | '/admin/org-structure'
    | '/admin/procurement'
    | '/admin/settings'
    | '/admin/transport'
    | '/analytics/reports'
    | '/communication/announcements'
    | '/communication/inbox'
    | '/compliance/aicte'
    | '/compliance/naac'
    | '/compliance/nba'
    | '/compliance/nirf'
    | '/finance/budget'
    | '/finance/defaulters'
    | '/finance/fee-structures'
    | '/finance/ledger'
    | '/finance/scholarships'
    | '/my/fees'
    | '/my/results'
    | '/people/alumni'
    | '/people/faculty'
    | '/people/faculty-appraisal'
    | '/people/parents'
    | '/people/students'
    | '/placement/ai-assessments'
    | '/placement/ai-interviews'
    | '/placement/companies'
    | '/placement/drives'
    | '/placement/job-profiles'
    | '/placement/offers'
    | '/quality/grievances'
    | '/quality/iqac'
    | '/quality/research'
    | '/admissions'
    | '/academic/examinations/$id'
    | '/admin/access-control/access-packs'
    | '/admin/access-control/activity'
    | '/admin/access-control/people'
    | '/admin/access-control/requests'
    | '/people/students/$id'
    | '/placement/ai-assessments/take'
    | '/placement/drives/$id'
    | '/admin/access-control'
    | '/admin/access-control/access-packs/$id'
    | '/admin/access-control/users/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/_app/$'
    | '/_app/access-denied'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/academic/attendance'
    | '/_app/academic/calendar'
    | '/_app/academic/certificates'
    | '/_app/academic/classes'
    | '/_app/academic/course-files'
    | '/_app/academic/examinations'
    | '/_app/academic/library'
    | '/_app/academic/programs'
    | '/_app/academic/results'
    | '/_app/academic/study-material'
    | '/_app/academic/subjects'
    | '/_app/academic/timetable'
    | '/_app/admin/approvals'
    | '/_app/admin/audit-log'
    | '/_app/admin/committees'
    | '/_app/admin/hostel'
    | '/_app/admin/org-structure'
    | '/_app/admin/procurement'
    | '/_app/admin/settings'
    | '/_app/admin/transport'
    | '/_app/analytics/reports'
    | '/_app/communication/announcements'
    | '/_app/communication/inbox'
    | '/_app/compliance/aicte'
    | '/_app/compliance/naac'
    | '/_app/compliance/nba'
    | '/_app/compliance/nirf'
    | '/_app/finance/budget'
    | '/_app/finance/defaulters'
    | '/_app/finance/fee-structures'
    | '/_app/finance/ledger'
    | '/_app/finance/scholarships'
    | '/_app/my/fees'
    | '/_app/my/results'
    | '/_app/people/alumni'
    | '/_app/people/faculty'
    | '/_app/people/faculty-appraisal'
    | '/_app/people/parents'
    | '/_app/people/students'
    | '/_app/placement/ai-assessments'
    | '/_app/placement/ai-interviews'
    | '/_app/placement/companies'
    | '/_app/placement/drives'
    | '/_app/placement/job-profiles'
    | '/_app/placement/offers'
    | '/_app/quality/grievances'
    | '/_app/quality/iqac'
    | '/_app/quality/research'
    | '/_app/admissions/'
    | '/_app/academic/examinations/$id'
    | '/_app/admin/access-control/access-packs'
    | '/_app/admin/access-control/activity'
    | '/_app/admin/access-control/people'
    | '/_app/admin/access-control/requests'
    | '/_app/people/students/$id'
    | '/_app/placement/ai-assessments/take'
    | '/_app/placement/drives/$id'
    | '/_app/admin/access-control/'
    | '/_app/admin/access-control/access-packs/$id'
    | '/_app/admin/access-control/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access-denied': {
      id: '/_app/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AppAccessDeniedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admissions/': {
      id: '/_app/admissions/'
      path: '/admissions'
      fullPath: '/admissions/'
      preLoaderRoute: typeof AppAdmissionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality/research': {
      id: '/_app/quality/research'
      path: '/quality/research'
      fullPath: '/quality/research'
      preLoaderRoute: typeof AppQualityResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality/iqac': {
      id: '/_app/quality/iqac'
      path: '/quality/iqac'
      fullPath: '/quality/iqac'
      preLoaderRoute: typeof AppQualityIqacRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality/grievances': {
      id: '/_app/quality/grievances'
      path: '/quality/grievances'
      fullPath: '/quality/grievances'
      preLoaderRoute: typeof AppQualityGrievancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/placement/offers': {
      id: '/_app/placement/offers'
      path: '/placement/offers'
      fullPath: '/placement/offers'
      preLoaderRoute: typeof AppPlacementOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/placement/job-profiles': {
      id: '/_app/placement/job-profiles'
      path: '/placement/job-profiles'
      fullPath: '/placement/job-profiles'
      preLoaderRoute: typeof AppPlacementJobProfilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/placement/drives': {
      id: '/_app/placement/drives'
      path: '/placement/drives'
      fullPath: '/placement/drives'
      preLoaderRoute: typeof AppPlacementDrivesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/placement/companies': {
      id: '/_app/placement/companies'
      path: '/placement/companies'
      fullPath: '/placement/companies'
      preLoaderRoute: typeof AppPlacementCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/placement/ai-interviews': {
      id: '/_app/placement/ai-interviews'
      path: '/placement/ai-interviews'
      fullPath: '/placement/ai-interviews'
      preLoaderRoute: typeof AppPlacementAiInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/placement/ai-assessments': {
      id: '/_app/placement/ai-assessments'
      path: '/placement/ai-assessments'
      fullPath: '/placement/ai-assessments'
      preLoaderRoute: typeof AppPlacementAiAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/students': {
      id: '/_app/people/students'
      path: '/people/students'
      fullPath: '/people/students'
      preLoaderRoute: typeof AppPeopleStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/parents': {
      id: '/_app/people/parents'
      path: '/people/parents'
      fullPath: '/people/parents'
      preLoaderRoute: typeof AppPeopleParentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/faculty-appraisal': {
      id: '/_app/people/faculty-appraisal'
      path: '/people/faculty-appraisal'
      fullPath: '/people/faculty-appraisal'
      preLoaderRoute: typeof AppPeopleFacultyAppraisalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/faculty': {
      id: '/_app/people/faculty'
      path: '/people/faculty'
      fullPath: '/people/faculty'
      preLoaderRoute: typeof AppPeopleFacultyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/alumni': {
      id: '/_app/people/alumni'
      path: '/people/alumni'
      fullPath: '/people/alumni'
      preLoaderRoute: typeof AppPeopleAlumniRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my/results': {
      id: '/_app/my/results'
      path: '/my/results'
      fullPath: '/my/results'
      preLoaderRoute: typeof AppMyResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my/fees': {
      id: '/_app/my/fees'
      path: '/my/fees'
      fullPath: '/my/fees'
      preLoaderRoute: typeof AppMyFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/scholarships': {
      id: '/_app/finance/scholarships'
      path: '/finance/scholarships'
      fullPath: '/finance/scholarships'
      preLoaderRoute: typeof AppFinanceScholarshipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/ledger': {
      id: '/_app/finance/ledger'
      path: '/finance/ledger'
      fullPath: '/finance/ledger'
      preLoaderRoute: typeof AppFinanceLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/fee-structures': {
      id: '/_app/finance/fee-structures'
      path: '/finance/fee-structures'
      fullPath: '/finance/fee-structures'
      preLoaderRoute: typeof AppFinanceFeeStructuresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/defaulters': {
      id: '/_app/finance/defaulters'
      path: '/finance/defaulters'
      fullPath: '/finance/defaulters'
      preLoaderRoute: typeof AppFinanceDefaultersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/budget': {
      id: '/_app/finance/budget'
      path: '/finance/budget'
      fullPath: '/finance/budget'
      preLoaderRoute: typeof AppFinanceBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance/nirf': {
      id: '/_app/compliance/nirf'
      path: '/compliance/nirf'
      fullPath: '/compliance/nirf'
      preLoaderRoute: typeof AppComplianceNirfRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance/nba': {
      id: '/_app/compliance/nba'
      path: '/compliance/nba'
      fullPath: '/compliance/nba'
      preLoaderRoute: typeof AppComplianceNbaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance/naac': {
      id: '/_app/compliance/naac'
      path: '/compliance/naac'
      fullPath: '/compliance/naac'
      preLoaderRoute: typeof AppComplianceNaacRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance/aicte': {
      id: '/_app/compliance/aicte'
      path: '/compliance/aicte'
      fullPath: '/compliance/aicte'
      preLoaderRoute: typeof AppComplianceAicteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communication/inbox': {
      id: '/_app/communication/inbox'
      path: '/communication/inbox'
      fullPath: '/communication/inbox'
      preLoaderRoute: typeof AppCommunicationInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communication/announcements': {
      id: '/_app/communication/announcements'
      path: '/communication/announcements'
      fullPath: '/communication/announcements'
      preLoaderRoute: typeof AppCommunicationAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics/reports': {
      id: '/_app/analytics/reports'
      path: '/analytics/reports'
      fullPath: '/analytics/reports'
      preLoaderRoute: typeof AppAnalyticsReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/transport': {
      id: '/_app/admin/transport'
      path: '/admin/transport'
      fullPath: '/admin/transport'
      preLoaderRoute: typeof AppAdminTransportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/procurement': {
      id: '/_app/admin/procurement'
      path: '/admin/procurement'
      fullPath: '/admin/procurement'
      preLoaderRoute: typeof AppAdminProcurementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/org-structure': {
      id: '/_app/admin/org-structure'
      path: '/admin/org-structure'
      fullPath: '/admin/org-structure'
      preLoaderRoute: typeof AppAdminOrgStructureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/hostel': {
      id: '/_app/admin/hostel'
      path: '/admin/hostel'
      fullPath: '/admin/hostel'
      preLoaderRoute: typeof AppAdminHostelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/committees': {
      id: '/_app/admin/committees'
      path: '/admin/committees'
      fullPath: '/admin/committees'
      preLoaderRoute: typeof AppAdminCommitteesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit-log': {
      id: '/_app/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AppAdminAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/approvals': {
      id: '/_app/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AppAdminApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/timetable': {
      id: '/_app/academic/timetable'
      path: '/academic/timetable'
      fullPath: '/academic/timetable'
      preLoaderRoute: typeof AppAcademicTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/subjects': {
      id: '/_app/academic/subjects'
      path: '/academic/subjects'
      fullPath: '/academic/subjects'
      preLoaderRoute: typeof AppAcademicSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/study-material': {
      id: '/_app/academic/study-material'
      path: '/academic/study-material'
      fullPath: '/academic/study-material'
      preLoaderRoute: typeof AppAcademicStudyMaterialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/results': {
      id: '/_app/academic/results'
      path: '/academic/results'
      fullPath: '/academic/results'
      preLoaderRoute: typeof AppAcademicResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/programs': {
      id: '/_app/academic/programs'
      path: '/academic/programs'
      fullPath: '/academic/programs'
      preLoaderRoute: typeof AppAcademicProgramsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/library': {
      id: '/_app/academic/library'
      path: '/academic/library'
      fullPath: '/academic/library'
      preLoaderRoute: typeof AppAcademicLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/examinations': {
      id: '/_app/academic/examinations'
      path: '/academic/examinations'
      fullPath: '/academic/examinations'
      preLoaderRoute: typeof AppAcademicExaminationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/course-files': {
      id: '/_app/academic/course-files'
      path: '/academic/course-files'
      fullPath: '/academic/course-files'
      preLoaderRoute: typeof AppAcademicCourseFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/classes': {
      id: '/_app/academic/classes'
      path: '/academic/classes'
      fullPath: '/academic/classes'
      preLoaderRoute: typeof AppAcademicClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/certificates': {
      id: '/_app/academic/certificates'
      path: '/academic/certificates'
      fullPath: '/academic/certificates'
      preLoaderRoute: typeof AppAcademicCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/calendar': {
      id: '/_app/academic/calendar'
      path: '/academic/calendar'
      fullPath: '/academic/calendar'
      preLoaderRoute: typeof AppAcademicCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/attendance': {
      id: '/_app/academic/attendance'
      path: '/academic/attendance'
      fullPath: '/academic/attendance'
      preLoaderRoute: typeof AppAcademicAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/access-control/': {
      id: '/_app/admin/access-control/'
      path: '/admin/access-control'
      fullPath: '/admin/access-control/'
      preLoaderRoute: typeof AppAdminAccessControlIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/placement/drives/$id': {
      id: '/_app/placement/drives/$id'
      path: '/$id'
      fullPath: '/placement/drives/$id'
      preLoaderRoute: typeof AppPlacementDrivesIdRouteImport
      parentRoute: typeof AppPlacementDrivesRoute
    }
    '/_app/placement/ai-assessments/take': {
      id: '/_app/placement/ai-assessments/take'
      path: '/take'
      fullPath: '/placement/ai-assessments/take'
      preLoaderRoute: typeof AppPlacementAiAssessmentsTakeRouteImport
      parentRoute: typeof AppPlacementAiAssessmentsRoute
    }
    '/_app/people/students/$id': {
      id: '/_app/people/students/$id'
      path: '/$id'
      fullPath: '/people/students/$id'
      preLoaderRoute: typeof AppPeopleStudentsIdRouteImport
      parentRoute: typeof AppPeopleStudentsRoute
    }
    '/_app/admin/access-control/requests': {
      id: '/_app/admin/access-control/requests'
      path: '/admin/access-control/requests'
      fullPath: '/admin/access-control/requests'
      preLoaderRoute: typeof AppAdminAccessControlRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/access-control/people': {
      id: '/_app/admin/access-control/people'
      path: '/admin/access-control/people'
      fullPath: '/admin/access-control/people'
      preLoaderRoute: typeof AppAdminAccessControlPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/access-control/activity': {
      id: '/_app/admin/access-control/activity'
      path: '/admin/access-control/activity'
      fullPath: '/admin/access-control/activity'
      preLoaderRoute: typeof AppAdminAccessControlActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/access-control/access-packs': {
      id: '/_app/admin/access-control/access-packs'
      path: '/admin/access-control/access-packs'
      fullPath: '/admin/access-control/access-packs'
      preLoaderRoute: typeof AppAdminAccessControlAccessPacksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/examinations/$id': {
      id: '/_app/academic/examinations/$id'
      path: '/$id'
      fullPath: '/academic/examinations/$id'
      preLoaderRoute: typeof AppAcademicExaminationsIdRouteImport
      parentRoute: typeof AppAcademicExaminationsRoute
    }
    '/_app/admin/access-control/users/$id': {
      id: '/_app/admin/access-control/users/$id'
      path: '/admin/access-control/users/$id'
      fullPath: '/admin/access-control/users/$id'
      preLoaderRoute: typeof AppAdminAccessControlUsersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/access-control/access-packs/$id': {
      id: '/_app/admin/access-control/access-packs/$id'
      path: '/$id'
      fullPath: '/admin/access-control/access-packs/$id'
      preLoaderRoute: typeof AppAdminAccessControlAccessPacksIdRouteImport
      parentRoute: typeof AppAdminAccessControlAccessPacksRoute
    }
  }
}

interface AppAcademicExaminationsRouteChildren {
  AppAcademicExaminationsIdRoute: typeof AppAcademicExaminationsIdRoute
}

const AppAcademicExaminationsRouteChildren: AppAcademicExaminationsRouteChildren =
  {
    AppAcademicExaminationsIdRoute: AppAcademicExaminationsIdRoute,
  }

const AppAcademicExaminationsRouteWithChildren =
  AppAcademicExaminationsRoute._addFileChildren(
    AppAcademicExaminationsRouteChildren,
  )

interface AppPeopleStudentsRouteChildren {
  AppPeopleStudentsIdRoute: typeof AppPeopleStudentsIdRoute
}

const AppPeopleStudentsRouteChildren: AppPeopleStudentsRouteChildren = {
  AppPeopleStudentsIdRoute: AppPeopleStudentsIdRoute,
}

const AppPeopleStudentsRouteWithChildren =
  AppPeopleStudentsRoute._addFileChildren(AppPeopleStudentsRouteChildren)

interface AppPlacementAiAssessmentsRouteChildren {
  AppPlacementAiAssessmentsTakeRoute: typeof AppPlacementAiAssessmentsTakeRoute
}

const AppPlacementAiAssessmentsRouteChildren: AppPlacementAiAssessmentsRouteChildren =
  {
    AppPlacementAiAssessmentsTakeRoute: AppPlacementAiAssessmentsTakeRoute,
  }

const AppPlacementAiAssessmentsRouteWithChildren =
  AppPlacementAiAssessmentsRoute._addFileChildren(
    AppPlacementAiAssessmentsRouteChildren,
  )

interface AppPlacementDrivesRouteChildren {
  AppPlacementDrivesIdRoute: typeof AppPlacementDrivesIdRoute
}

const AppPlacementDrivesRouteChildren: AppPlacementDrivesRouteChildren = {
  AppPlacementDrivesIdRoute: AppPlacementDrivesIdRoute,
}

const AppPlacementDrivesRouteWithChildren =
  AppPlacementDrivesRoute._addFileChildren(AppPlacementDrivesRouteChildren)

interface AppAdminAccessControlAccessPacksRouteChildren {
  AppAdminAccessControlAccessPacksIdRoute: typeof AppAdminAccessControlAccessPacksIdRoute
}

const AppAdminAccessControlAccessPacksRouteChildren: AppAdminAccessControlAccessPacksRouteChildren =
  {
    AppAdminAccessControlAccessPacksIdRoute:
      AppAdminAccessControlAccessPacksIdRoute,
  }

const AppAdminAccessControlAccessPacksRouteWithChildren =
  AppAdminAccessControlAccessPacksRoute._addFileChildren(
    AppAdminAccessControlAccessPacksRouteChildren,
  )

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAccessDeniedRoute: typeof AppAccessDeniedRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppAcademicAttendanceRoute: typeof AppAcademicAttendanceRoute
  AppAcademicCalendarRoute: typeof AppAcademicCalendarRoute
  AppAcademicCertificatesRoute: typeof AppAcademicCertificatesRoute
  AppAcademicClassesRoute: typeof AppAcademicClassesRoute
  AppAcademicCourseFilesRoute: typeof AppAcademicCourseFilesRoute
  AppAcademicExaminationsRoute: typeof AppAcademicExaminationsRouteWithChildren
  AppAcademicLibraryRoute: typeof AppAcademicLibraryRoute
  AppAcademicProgramsRoute: typeof AppAcademicProgramsRoute
  AppAcademicResultsRoute: typeof AppAcademicResultsRoute
  AppAcademicStudyMaterialRoute: typeof AppAcademicStudyMaterialRoute
  AppAcademicSubjectsRoute: typeof AppAcademicSubjectsRoute
  AppAcademicTimetableRoute: typeof AppAcademicTimetableRoute
  AppAdminApprovalsRoute: typeof AppAdminApprovalsRoute
  AppAdminAuditLogRoute: typeof AppAdminAuditLogRoute
  AppAdminCommitteesRoute: typeof AppAdminCommitteesRoute
  AppAdminHostelRoute: typeof AppAdminHostelRoute
  AppAdminOrgStructureRoute: typeof AppAdminOrgStructureRoute
  AppAdminProcurementRoute: typeof AppAdminProcurementRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminTransportRoute: typeof AppAdminTransportRoute
  AppAnalyticsReportsRoute: typeof AppAnalyticsReportsRoute
  AppCommunicationAnnouncementsRoute: typeof AppCommunicationAnnouncementsRoute
  AppCommunicationInboxRoute: typeof AppCommunicationInboxRoute
  AppComplianceAicteRoute: typeof AppComplianceAicteRoute
  AppComplianceNaacRoute: typeof AppComplianceNaacRoute
  AppComplianceNbaRoute: typeof AppComplianceNbaRoute
  AppComplianceNirfRoute: typeof AppComplianceNirfRoute
  AppFinanceBudgetRoute: typeof AppFinanceBudgetRoute
  AppFinanceDefaultersRoute: typeof AppFinanceDefaultersRoute
  AppFinanceFeeStructuresRoute: typeof AppFinanceFeeStructuresRoute
  AppFinanceLedgerRoute: typeof AppFinanceLedgerRoute
  AppFinanceScholarshipsRoute: typeof AppFinanceScholarshipsRoute
  AppMyFeesRoute: typeof AppMyFeesRoute
  AppMyResultsRoute: typeof AppMyResultsRoute
  AppPeopleAlumniRoute: typeof AppPeopleAlumniRoute
  AppPeopleFacultyRoute: typeof AppPeopleFacultyRoute
  AppPeopleFacultyAppraisalRoute: typeof AppPeopleFacultyAppraisalRoute
  AppPeopleParentsRoute: typeof AppPeopleParentsRoute
  AppPeopleStudentsRoute: typeof AppPeopleStudentsRouteWithChildren
  AppPlacementAiAssessmentsRoute: typeof AppPlacementAiAssessmentsRouteWithChildren
  AppPlacementAiInterviewsRoute: typeof AppPlacementAiInterviewsRoute
  AppPlacementCompaniesRoute: typeof AppPlacementCompaniesRoute
  AppPlacementDrivesRoute: typeof AppPlacementDrivesRouteWithChildren
  AppPlacementJobProfilesRoute: typeof AppPlacementJobProfilesRoute
  AppPlacementOffersRoute: typeof AppPlacementOffersRoute
  AppQualityGrievancesRoute: typeof AppQualityGrievancesRoute
  AppQualityIqacRoute: typeof AppQualityIqacRoute
  AppQualityResearchRoute: typeof AppQualityResearchRoute
  AppAdmissionsIndexRoute: typeof AppAdmissionsIndexRoute
  AppAdminAccessControlAccessPacksRoute: typeof AppAdminAccessControlAccessPacksRouteWithChildren
  AppAdminAccessControlActivityRoute: typeof AppAdminAccessControlActivityRoute
  AppAdminAccessControlPeopleRoute: typeof AppAdminAccessControlPeopleRoute
  AppAdminAccessControlRequestsRoute: typeof AppAdminAccessControlRequestsRoute
  AppAdminAccessControlIndexRoute: typeof AppAdminAccessControlIndexRoute
  AppAdminAccessControlUsersIdRoute: typeof AppAdminAccessControlUsersIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAccessDeniedRoute: AppAccessDeniedRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppAcademicAttendanceRoute: AppAcademicAttendanceRoute,
  AppAcademicCalendarRoute: AppAcademicCalendarRoute,
  AppAcademicCertificatesRoute: AppAcademicCertificatesRoute,
  AppAcademicClassesRoute: AppAcademicClassesRoute,
  AppAcademicCourseFilesRoute: AppAcademicCourseFilesRoute,
  AppAcademicExaminationsRoute: AppAcademicExaminationsRouteWithChildren,
  AppAcademicLibraryRoute: AppAcademicLibraryRoute,
  AppAcademicProgramsRoute: AppAcademicProgramsRoute,
  AppAcademicResultsRoute: AppAcademicResultsRoute,
  AppAcademicStudyMaterialRoute: AppAcademicStudyMaterialRoute,
  AppAcademicSubjectsRoute: AppAcademicSubjectsRoute,
  AppAcademicTimetableRoute: AppAcademicTimetableRoute,
  AppAdminApprovalsRoute: AppAdminApprovalsRoute,
  AppAdminAuditLogRoute: AppAdminAuditLogRoute,
  AppAdminCommitteesRoute: AppAdminCommitteesRoute,
  AppAdminHostelRoute: AppAdminHostelRoute,
  AppAdminOrgStructureRoute: AppAdminOrgStructureRoute,
  AppAdminProcurementRoute: AppAdminProcurementRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminTransportRoute: AppAdminTransportRoute,
  AppAnalyticsReportsRoute: AppAnalyticsReportsRoute,
  AppCommunicationAnnouncementsRoute: AppCommunicationAnnouncementsRoute,
  AppCommunicationInboxRoute: AppCommunicationInboxRoute,
  AppComplianceAicteRoute: AppComplianceAicteRoute,
  AppComplianceNaacRoute: AppComplianceNaacRoute,
  AppComplianceNbaRoute: AppComplianceNbaRoute,
  AppComplianceNirfRoute: AppComplianceNirfRoute,
  AppFinanceBudgetRoute: AppFinanceBudgetRoute,
  AppFinanceDefaultersRoute: AppFinanceDefaultersRoute,
  AppFinanceFeeStructuresRoute: AppFinanceFeeStructuresRoute,
  AppFinanceLedgerRoute: AppFinanceLedgerRoute,
  AppFinanceScholarshipsRoute: AppFinanceScholarshipsRoute,
  AppMyFeesRoute: AppMyFeesRoute,
  AppMyResultsRoute: AppMyResultsRoute,
  AppPeopleAlumniRoute: AppPeopleAlumniRoute,
  AppPeopleFacultyRoute: AppPeopleFacultyRoute,
  AppPeopleFacultyAppraisalRoute: AppPeopleFacultyAppraisalRoute,
  AppPeopleParentsRoute: AppPeopleParentsRoute,
  AppPeopleStudentsRoute: AppPeopleStudentsRouteWithChildren,
  AppPlacementAiAssessmentsRoute: AppPlacementAiAssessmentsRouteWithChildren,
  AppPlacementAiInterviewsRoute: AppPlacementAiInterviewsRoute,
  AppPlacementCompaniesRoute: AppPlacementCompaniesRoute,
  AppPlacementDrivesRoute: AppPlacementDrivesRouteWithChildren,
  AppPlacementJobProfilesRoute: AppPlacementJobProfilesRoute,
  AppPlacementOffersRoute: AppPlacementOffersRoute,
  AppQualityGrievancesRoute: AppQualityGrievancesRoute,
  AppQualityIqacRoute: AppQualityIqacRoute,
  AppQualityResearchRoute: AppQualityResearchRoute,
  AppAdmissionsIndexRoute: AppAdmissionsIndexRoute,
  AppAdminAccessControlAccessPacksRoute:
    AppAdminAccessControlAccessPacksRouteWithChildren,
  AppAdminAccessControlActivityRoute: AppAdminAccessControlActivityRoute,
  AppAdminAccessControlPeopleRoute: AppAdminAccessControlPeopleRoute,
  AppAdminAccessControlRequestsRoute: AppAdminAccessControlRequestsRoute,
  AppAdminAccessControlIndexRoute: AppAdminAccessControlIndexRoute,
  AppAdminAccessControlUsersIdRoute: AppAdminAccessControlUsersIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
